/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001849",
        "surface-container-high": "#252a39",
        "inverse-surface": "#dee2f6",
        "background": "#0e1321",
        "on-tertiary": "#003061",
        "secondary-fixed-dim": "#47d6ff",
        "on-error": "#690005",
        "surface-bright": "#343948",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004689",
        "surface-tint": "#b3c5ff",
        "inverse-on-surface": "#2b303f",
        "inverse-primary": "#0054d6",
        "on-secondary-fixed": "#001f28",
        "tertiary-container": "#0071d6",
        "tertiary-fixed": "#d5e3ff",
        "primary-container": "#0066ff",
        "outline-variant": "#424656",
        "on-primary-fixed-variant": "#003fa4",
        "surface-container-highest": "#303444",
        "on-secondary": "#003543",
        "surface-container-low": "#161b2a",
        "surface-variant": "#303444",
        "secondary-container": "#00d2ff",
        "secondary": "#a5e7ff",
        "on-tertiary-fixed": "#001b3c",
        "outline": "#8c90a1",
        "primary-fixed": "#dae1ff",
        "surface-dim": "#0e1321",
        "on-surface-variant": "#c2c6d8",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00566a",
        "secondary-fixed": "#b6ebff",
        "primary": "#b3c5ff",
        "tertiary-fixed-dim": "#a8c8ff",
        "on-primary-container": "#f8f7ff",
        "surface-container": "#1a1f2e",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container-lowest": "#090e1c",
        "surface": "#0e1321",
        "on-surface": "#dee2f6",
        "on-background": "#dee2f6",
        "error-container": "#93000a",
        "tertiary": "#a8c8ff",
        "error": "#ffb4ab",
        "on-tertiary-container": "#f6f7ff",
        "on-secondary-fixed-variant": "#004e60"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "4rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "margin-tablet": "2rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "display-hero": ["Outfit", "sans-serif"],
        "display-hero-mobile": ["Outfit", "sans-serif"],
        "headline-xl-mobile": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
